export const USER_NULL = 'User is null.';
export const ROLE_NOT_FOUND = 'Role not found.';
export const USER_CREATION_ERROR = 'Error during user creation.';
export const DB_CONNECTION_ERROR = 'Error during database connection.';
export const QUERY_EXECUTION_ERROR = 'Error during query execution.';
export const ENV_CONSTANT_ERROR = 'Environment constant not found.';
export const TOKEN_ERROR = 'Error in the provided token.';
export const TOKEN_NOT_FOUND = 'Token not found.'
export const WRONG_CREDENTIALS_ERROR = 'Email or password does not match.';
export const MODEL_NOT_FOUND_ERROR = 'Mongoose model not found.';
export const REGISTRATION_ERROR = 'Error during registration.'